# Generated by Django 5.0 on 2023-12-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together={('name', 'state', 'address')},
        ),
    ]
